server:
  port: 0
#  port: ${random.int(10000,51000)}

spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

#spring:
#  config:
#    import: optional:configserver:http://127.0.0.1:8888/
#  cloud:
#    config:
#      #      name: ecommerce
#      name: user-service
#  application:
#    name: user-service
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
#      path: /h2-console
#    jpa:
#      hibernate:
#        ddl-auto: update
#    datasource:
#      driver-class-name: org.h2.Driver
#      url: jdbc:h2:mem:testdb # jdbc:h2:tcp://localhost/mem:testdb
#      username: sa
#      password:


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

greeting:
  message: Welcome to the Simple E-commerce